name: dev-feisty
channels:
  - conda-forge
dependencies:
  - python=3.9
  - codecov
  - dask
  - dask-jobqueue
  - jupyter
  - jupyter-book
  - jupyter_client==6.1.12
  - jupyterlab
  - matplotlib
  - myst-nb
  - nbformat
  - nbsphinx
  - nc-time-axis
  - netcdf4
  - numpydoc
  - pip
  - pre-commit
  - pytest
  - pytest-cov
  - scipy
  - xarray
  - pip:
      - sphinx-click
      - sphinxcontrib-autoyaml
